
import './globals.css'
import Layout from "./components/layout/layout";
import { CartContextProvider } from './context/cartContext';
import AuthLayout from './context/authLayout';
import { getServerSession } from 'next-auth';


export const metadata = {
  title: 'Depot',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  

 
  const session = await getServerSession()
  return (
    <html lang="en">
           
      <body className="bg-white">
        
     
      <AuthLayout session={session}>
          <CartContextProvider  >
            <Layout>
              {children}
            </Layout>
          </CartContextProvider>
    </AuthLayout>
   

      </body>

    </html>
  )
} 